### ISSUE TITLE
Safari  16.0 with default Apple Safari Private Relay ignoring maza rules

### ISSUE THREAD

**Issue by his0ki** [tanrax/maza-ad-blocking#17]
Thanks for the awesome tool... just done some testing and it seems pretty good blocking in Chromium browsers, Opera and Edge (still see some googleads.g.doubleclick.net ads in Edge sites). 
Safari seems to completely disregard any rules, is there no way to handle the Safari issue which i am guessing is a side-effect of enabling Private Relay in the iCloud features

Cache cleared multiple times, maza updated stopped and restarted but no luck!
thanks

**Comment by tanrax** [comment]
I completely ignore how the new iCloud privacy system works. There should be no problem if you use a custom DNS server with Dnsmasq and configure your internet connection to use it. Otherwise they are already issues of the operating system itself that Maza can not enter, nor any other software.
Best regards
