### ISSUE TITLE
Cannot ignore t.co even after setting

### ISSUE THREAD

**Issue by alpineyahoo** [tanrax/maza-ad-blocking#29]
I tried to access [t.co](https://t.co) by setting /root/.config/maza/ignore file to ignore domains related to Twitter. However, that failed. Could anyone suggest why?
```sh
# /root/.config/maza/ignore file
t.co
ads-twitter.com
ads.twitter.com
```
I followed the official README [description](https://github.com/tanrax/maza-ad-blocking?tab=readme-ov-file#-not-blocking-certain-domains). I doubted that it was caused by the browser, but the same thing happened on the terminal (`curl` command) and I found that the browser was not the suspect.

**Comment by tanrax** [comment]
Hi! What is your goal? Do you want to block or unblock the domains? What does curl tell you?

**Comment by alpineyahoo** [comment]
@tanrax Thanks for your reply. I would like to "unblock" domains related to Twitter or t.co. `curl` works normally after running `sudo maza stop`, so I guess domains related to Twitter might not be removed from /etc/hosts even after setting /root/.config/maza/ignore file. It would be nice if you suggest some solution. There's a little chance that allowing the domains t.co, ads-twitter.com, ads.twitter.com are not enough to allow t.co.

**Comment by tanrax** [comment]
Hi @alpineyahoo 
I need to more context.
- What carrier system did you use?
- What content you have in the /root/.config/maza/ignore file?
- What version of bash are you running?
Thanks

**Comment by alpineyahoo** [comment]
@tanrax Here are the contexts below:
```sh
$ sw_vers
ProductName:		macOS
ProductVersion:		15.0
BuildVersion:		24A5298h
$ cat /root/.config/maza/ignore
t.co
ads-twitter.com
ads.twitter.com
$ zsh --version # I ran curl in zsh
zsh 5.9 (x86_64-apple-darwin21.3.0)
$ grep ' t.co' /etc/hosts
127.0.0.1 t.co
$ grep twitter /etc/hosts
127.0.0.1 ads-twitter.com
127.0.0.1 ads.twitter.com
```
Sadly, t.co, ads-twitter.com, and ads.twitter.com are in `/etc/hosts`.

**Comment by tanrax** [comment]
Sorry about you problem!

You would try:

1. First, update Maza

```sh
curl -o maza https://raw.githubusercontent.com/tanrax/maza-ad-blocking/master/maza && sudo rm -rf /usr/local/bin/maza && chmod +x maza && sudo mv maza /usr/local/bin
```

2. Check that you have `gnu-sed` installed.

```sh
brew install gnu-sed
```

3. Stop, update and start Maza.

```sh
sudo maza stop
```

Verify that `/etc/hosts` is clean.

```sh
sudo maza update
sudo maza start
```

And check again.

**Comment by alpineyahoo** [comment]
I followed your instructions above, but the problem still persists. Why do you think maza cannot find the ignore file? Is it an issue related to permission of files in /root/.config/maza ?
```sh
$ gstat /root/.config/maza | awk 'NR==4 {print $2}'
(0755/drwxr-xr-x)
$ gstat /root/.config/maza/ignore | awk 'NR==4 {print $2}'
(0644/-rw-r--r--)
```

**Comment by tanrax** [comment]
The code that process the `ignore` is this:

https://github.com/tanrax/maza-ad-blocking/blob/b2a4d7217b3144f1f3165286981625952faa3496/maza#L114-L122

It's very simple. The problem is outside.

- Ensure there are no extra spaces or hidden characters in the ignore list file. The entries should be plain text, one per line.
- Double-check the script to ensure that it correctly reads and processes the ignore list. Please, check the above code.
- Verify that the $CONFIG, $IGNORE_LIST_FILE, and $LIST variables are correctly set and point to the right files.
- Ensure the script has the necessary permissions to read and write the ignore list and DNS list files.

After updating the ignore list, flush your DNS cache to ensure changes take effect. This can usually be done with a command like sudo systemd-resolve --flush-caches or sudo dscacheutil -flushcache on macOS.

**Comment by tanrax** [comment]
I'm glad I was able to help.

«Please consider donating to this project or a related one. All the work that goes into it will probably never be paid for, but a small gesture can help keep it going longer, help get questions answered, and add new features. Thank you.»
